#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="$(getApplication)"

runApplication blockMesh -dict /home/analysis/FluidAnalysis/calculation/uniform/parallel
runApplication $application

#------------------------------------------------------------------------------
